language: cpp
compiler: gcc
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y
    - sudo apt-get update -qq

install:
    - sudo apt-get install qt56base
    - source /opt/qt5*/bin/qt5*-env.sh

script:
    - mkdir build
    - cd build
    - qmake PREFIX=/usr ..
    - make -j4

notifications:
    email: false

before_deploy:
    - sh ../ci/before_deploy.sh
    - export BUILD_ARCHIVE=$(ls *.zip)
    - echo "Deploying $BUILD_ARCHIVE"

deploy:
    provider: releases

    api_key:
        secure: $GITHUB_TOKEN

    file: $BUILD_ARCHIVE
    skip_cleanup: true
    on:
        tags: true