language: cpp
compiler: gcc
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y
    - sudo apt-get update -qq

install:
    - sudo apt-get install qt56base
    - source /opt/qt5*/bin/qt5*-env.sh

script:
    - qmake PREFIX=/usr
    - make -j4

notifications:
    email: false

deploy:
    provider: pages
    skip_cleanup: true
    project_name: PREF
    github_token: $GITHUB_TOKEN
    name: Travis Build Bot
    repo: PREF/pref.github.io
    on:
        branch: master