version: master

branches:
  only: 
    - master

skip_tags: true
skip_non_tags: true
clone_depth: 10
max_jobs: 4

install:
  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - qmake PREF.pro
  - mingw32-make