version: PREF_Windows_i686_{build}

branches:
  only: 
    - master

init:
- ps: Update-AppveyorBuild -Version "$(Get-Date -format dmY)_$env:appveyor_build_number"

environment:
  access_token:
    secure: 1xDbJm4/ZdjBTgkbzAHDtNOcsRwJz4u1GSfI4UEA2ZQYt1zFWURWu9+gyy9rEGck

skip_tags: true
skip_non_tags: true
max_jobs: 4

artifacts:
  - path: release\PREF.exe
    name: PREF-{build}

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - qmake CONFIG+=release ..
  - mingw32-make -j4