version: master-build-{build}

branches:
  only: 
    - master

skip_tags: true
skip_non_tags: true
max_jobs: 4

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.6\msvc2015_64
  - set PATH=%QTDIR%\bin;%PATH%
  - '%QTDIR%\bin\qtenv2.bat'
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64

build_script:
  - qmake PREF.pro
  - nmake /S /NOLOGO