version: master-build-{build}

branches:
  only: 
    - master

skip_tags: true
skip_non_tags: true
max_jobs: 4

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.6\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - qmake -v
  - nmake /S /NOLOGO