version: master-build-{build}

branches:
  only: 
    - master

skip_tags: true
skip_non_tags: true
max_jobs: 4

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%

build_script:
  - qmake PREF.pro CONFIG+=release
  - mingw32-make -j4