version: "{build}"

branches:
  only: 
    - master

init:
- ps: Update-AppveyorBuild -Version "PREF_Windows_i686_$(Get-Date -format ddMMyyyy)_$env:appveyor_build_number"

environment:
  build_repo: pref.github.io
  github_token:
    secure: 1xDbJm4/ZdjBTgkbzAHDtNOcsRwJz4u1GSfI4UEA2ZQYt1zFWURWu9+gyy9rEGck

skip_tags: true
skip_non_tags: true
max_jobs: 4

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - qmake CONFIG+=release ..
  - mingw32-make -j4
  - 7z a %APPVEYOR_BUILD_VERSION%.zip PREF\release\PREF.EXE
  - tree /f /a

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_token):x-oauth-basic@github.com`n"
  - ps: Remove-Item $($env:build_repo) -Recurse -Force 
  - start /B git clone -b builds https://${GITHUB_TOKEN}@github.com/PREF/$BUILD_REPO.git > NUL 2>&1
  - cd $(BUILD_REPO)
  - ps: Remove-Item *Windows* 
  - mv ../$(APPVEYOR_BUILD_VERSION).zip .
  - git config --global user.email "buildbot@none.io"
  - git config --global user.name "AppVeyor Build Bot"
  - git add -A .
  - git commit -m "Updated Windows Nightly $(Get-Date -format ddMMyyyy)"
  - ps: start /B git push --quiet origin builds > NULL 2>&1 