version: master-build-{build}

branches:
  only: 
    - master

skip_tags: true
skip_non_tags: true
max_jobs: 4

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - qmake PREF.pro
  - mingw32-make