version: "{build}"

branches:
  only: 
    - master

init:
- ps: Update-AppveyorBuild -Version "PREF_Windows_i686_$(Get-Date -format ddMMyyyy)_$env:appveyor_build_number"

environment:
  access_token:
    secure: 1xDbJm4/ZdjBTgkbzAHDtNOcsRwJz4u1GSfI4UEA2ZQYt1zFWURWu9+gyy9rEGck

skip_tags: true
skip_non_tags: true
max_jobs: 4

artifacts:
  - path: build\PREF\$(APPVEYOR_BUILD_VERSION).zip
    name: $(APPVEYOR_BUILD_VERSION)

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - qmake CONFIG+=release ..
  - mingw32-make -j4
  - 7z a %APPVEYOR_BUILD_VERSION%.zip release\PREF.EXE
  - tree /f /a