version: master-build-{build}

branches:
  only: 
    - master

skip_tags: true
skip_non_tags: true
max_jobs: 4

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.6\mingw49_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1

build_script:
  - qmake PREF.pro
  - mingw32-make